import { BaseSeeder } from '@adonisjs/lucid/seeders'
import VaccineSchedule from '#models/vaccine_schedule'
import { DateTime } from 'luxon'
import { v4 as uuidv4 } from 'uuid'

export default class VaccineSchedulesSeeder extends BaseSeeder {
  async run() {
    console.log('  📅 Seeding vaccine schedules...')
    
    // Check if required data exists
    const vaccineTypes = await import('#models/vaccine_type').then(m => m.default.query().select('id'))
    const patients = await import('#models/patient').then(m => m.default.query().select('id'))
    const users = await import('#models/user').then(m => m.default.query().select('id'))
    
    if (vaccineTypes.length === 0 || patients.length === 0 || users.length === 0) {
      console.log('⚠️  Skipping vaccine schedules - missing required data')
      return
    }
    
    const schedules = [
      // Calendrier VAT pour Aïcha Ndiaye (Grossesse)
      {
        tenantId: 1,
        patientId: 1, // Aïcha Ndiaye
        vaccineTypeId: 1, // VAT (Tétanos Maternel)
        assignedProviderId: 1, // Fatou Ba (sage-femme)
        scheduledDate: DateTime.now().plus({ days: 7 }),
        dueDate: DateTime.now().plus({ days: 14 }),
        doseNumber: 1,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'high' as const,
        notes: 'Première dose VAT pendant la grossesse à 20 SA. Patiente informée de l\'importance.',
        nextReminderDate: DateTime.now().plus({ days: 5 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: false
      },
      {
        tenantId: 1,
        patientId: 1, // Aïcha Ndiaye
        vaccineTypeId: 1, // VAT
        assignedProviderId: 1, // Fatou Ba
        scheduledDate: DateTime.now().plus({ weeks: 5 }),
        dueDate: DateTime.now().plus({ weeks: 5, days: 7 }),
        doseNumber: 2,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'high' as const,
        notes: 'Deuxième dose VAT (4 semaines après la première) à 24 SA. Compléter protection maternelle et néonatale.',
        nextReminderDate: DateTime.now().plus({ weeks: 4, days: 5 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: false
      },

      // Calendrier VAT pour Khadija Thiam (complété)
      {
        tenantId: 1,
        patientId: 1, // Khadija Thiam
        vaccineTypeId: 1, // VAT
        assignedProviderId: 1, // Fatou Ba
        scheduledDate: DateTime.now().minus({ weeks: 8 }),
        dueDate: DateTime.now().minus({ weeks: 8 }).plus({ days: 7 }),
        doseNumber: 1,
        isBooster: false,
        status: 'completed' as const,
        priority: 'high' as const,
        notes: 'Première dose VAT administrée à 24 SA. Patiente bien informée.',
        nextReminderDate: DateTime.now().minus({ weeks: 8, days: 2 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: true
      },
      {
        tenantId: 1,
        patientId: 1, // Khadija Thiam
        vaccineTypeId: 1, // VAT
        assignedProviderId: 1, // Fatou Ba
        scheduledDate: DateTime.now().minus({ weeks: 4 }),
        dueDate: DateTime.now().minus({ weeks: 4 }).plus({ days: 7 }),
        doseNumber: 2,
        isBooster: false,
        status: 'completed' as const,
        priority: 'high' as const,
        notes: 'Deuxième dose VAT administrée à 28 SA. Protection complète acquise.',
        nextReminderDate: DateTime.now().minus({ weeks: 4, days: 2 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: true
      },

      // Calendrier vaccination enfant (exemple futur - enfant de Khadija)
      {
        tenantId: 1,
        patientId: 1, // Future mère
        vaccineTypeId: 1, // BCG 
        assignedProviderId: 1, // Fatou Ba
        scheduledDate: DateTime.now().plus({ weeks: 8, days: 3 }), // 3 jours après DPA
        dueDate: DateTime.now().plus({ weeks: 8, days: 10 }),
        doseNumber: 1,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'high' as const,
        notes: 'BCG à la naissance pour le futur nouveau-né. À programmer après accouchement.',
        nextReminderDate: DateTime.now().plus({ weeks: 8 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: false
      },
      {
        tenantId: 1,
        patientId: 1, // Future mère
        vaccineTypeId: 2, // Pentavalent
        assignedProviderId: 1, // Fatou Ba
        scheduledDate: DateTime.now().plus({ weeks: 14 }), // 6 semaines après naissance
        dueDate: DateTime.now().plus({ weeks: 14, days: 7 }),
        doseNumber: 1,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'normal' as const,
        notes: 'Première dose Pentavalent à 6 semaines pour le futur nouveau-né.',
        nextReminderDate: DateTime.now().plus({ weeks: 13 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: false
      },

      // Tenant 2 - Clinique Almadies
      {
        tenantId: 2,
        patientId: 7, // Patient Almadies
        vaccineTypeId: 1, // VAT
        assignedProviderId: 7, // Mariama Sy
        scheduledDate: DateTime.now().plus({ weeks: 12 }),
        dueDate: DateTime.now().plus({ weeks: 12, days: 7 }),
        doseNumber: 1,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'normal' as const,
        notes: 'Première dose VAT programmée pour 24 SA',
        nextReminderDate: DateTime.now().plus({ weeks: 11 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 7,
        isSynced: false
      },

      // Tenant 4 - Demo
      {
        tenantId: 4,
        patientId: 12, // Patiente Demo
        vaccineTypeId: 1, // VAT
        assignedProviderId: 11, // Sage-femme Demo
        scheduledDate: DateTime.now().plus({ weeks: 8 }),
        dueDate: DateTime.now().plus({ weeks: 8, days: 7 }),
        doseNumber: 1,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'high' as const,
        notes: 'Première dose VAT - Calendrier de démonstration',
        nextReminderDate: DateTime.now().plus({ weeks: 7 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 11,
        isSynced: false
      },
      {
        tenantId: 4,
        patientId: 12, // Patiente Demo
        vaccineTypeId: 1, // VAT
        assignedProviderId: 11, // Sage-femme Demo
        scheduledDate: DateTime.now().plus({ weeks: 12 }),
        dueDate: DateTime.now().plus({ weeks: 12, days: 7 }),
        doseNumber: 2,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'high' as const,
        notes: 'Deuxième dose VAT - Calendrier de démonstration',
        nextReminderDate: DateTime.now().plus({ weeks: 11 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 11,
        isSynced: false
      },

      // Exemples de vaccinations enfants (calendrier PEV Sénégal)
      {
        tenantId: 1,
        patientId: 1, // Futur enfant d'Aïcha
        vaccineTypeId: 1, // BCG
        assignedProviderId: 1, // Fatou Ba
        scheduledDate: DateTime.now().plus({ weeks: 20, days: 1 }), // 1 jour après DPA
        dueDate: DateTime.now().plus({ weeks: 20, days: 8 }),
        doseNumber: 1,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'urgent',
        notes: 'BCG à administrer dans les 24-48h après naissance',
        nextReminderDate: DateTime.now().plus({ weeks: 20 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: false
      },
      {
        tenantId: 1,
        patientId: 1, // Futur enfant d'Aïcha
        vaccineTypeId: 2, // Pentavalent
        assignedProviderId: 1, // Fatou Ba
        scheduledDate: DateTime.now().plus({ weeks: 26 }), // 6 semaines après naissance
        dueDate: DateTime.now().plus({ weeks: 26, days: 7 }),
        doseNumber: 1,
        isBooster: false,
        status: 'scheduled' as const,
        priority: 'high' as const,
        notes: 'Première dose Pentavalent selon calendrier PEV à 6 semaines',
        nextReminderDate: DateTime.now().plus({ weeks: 25 }),
        reminderSent: false,
        reminderCount: 0,
        autoGenerated: false,
        canCoAdminister: true,
        isMandatory: true,
        syncId: uuidv4(),
        version: 1,
        createdBy: 1,
        isSynced: false
      }
    ]

    await VaccineSchedule.createMany(schedules)
  }
}