import { BaseSeeder } from '@adonisjs/lucid/seeders'
import VaccineType from '#models/vaccine_type'
import { v4 as uuidv4 } from 'uuid'

export default class VaccineTypesSeeder extends BaseSeeder {
  async run() {
    console.log('  💉 Seeding vaccine types...')
    
    await VaccineType.createMany([
      {
        name: 'BCG',
        code: 'BCG-001',
        description: 'Vaccin contre la tuberculose',
        manufacturer: 'Institut Pasteur Dakar',
        brandName: 'BCG-IPD',
        vaccineType: 'live',
        targetGroup: 'infant',
        minAgeMonths: 0,
        maxAgeMonths: 12,
        route: 'intradermal',
        site: 'Bras droit',
        doseVolume: 0.1,
        dosesRequired: 1,
        scheduleIntervals: [0],
        boosterIntervalMonths: null,
        requiresBooster: false,
        storageTempMin: 2,
        storageTempMax: 8,
        shelfLifeMonths: 24,
        storageInstructions: 'Conserver entre 2-8C',
        contraindications: ['immunodeficience', 'fievre'],
        precautions: ['prematurite'],
        sideEffects: ['rougeur_locale'],
        adverseReactions: ['lymphadenite'],
        diseasesPrevented: ['tuberculose'],
        efficacyRate: '70-80%',
        immunityDurationYears: 10,
        isWhoApproved: true,
        isNationalProgram: true,
        isMandatory: true,
        priorityLevel: 1,
        status: 'active',
        syncId: uuidv4(),
        version: 1,
        isSynced: false
      },
      {
        name: 'Pentavalent',
        code: 'PENTA-001',
        description: 'Vaccin pentavalent DTC-HepB-Hib',
        manufacturer: 'Serum Institute',
        brandName: 'Pentavac',
        vaccineType: 'inactivated',
        targetGroup: 'infant',
        minAgeMonths: 1.5,
        maxAgeMonths: 18,
        route: 'intramuscular',
        site: 'Cuisse',
        doseVolume: 0.5,
        dosesRequired: 3,
        scheduleIntervals: [6, 10, 14],
        boosterIntervalMonths: null,
        requiresBooster: false,
        storageTempMin: 2,
        storageTempMax: 8,
        shelfLifeMonths: 36,
        storageInstructions: 'Conserver entre 2-8C',
        contraindications: ['allergie_grave'],
        precautions: ['convulsions_febriles'],
        sideEffects: ['fievre_legere', 'douleur'],
        adverseReactions: ['convulsions'],
        diseasesPrevented: ['diphterie', 'tetanos', 'coqueluche', 'hepatite_b'],
        efficacyRate: '85-95%',
        immunityDurationYears: 10,
        isWhoApproved: true,
        isNationalProgram: true,
        isMandatory: true,
        priorityLevel: 2,
        status: 'active',
        syncId: uuidv4(),
        version: 1,
        isSynced: false
      },
      {
        name: 'VAT',
        code: 'TT-MAT-001',
        description: 'Vaccin antitetanique maternel',
        manufacturer: 'Serum Institute',
        brandName: 'Tetanol',
        vaccineType: 'toxoid',
        targetGroup: 'pregnant_women',
        minAgeMonths: 180,
        maxAgeMonths: 588,
        route: 'intramuscular',
        site: 'Deltoide',
        doseVolume: 0.5,
        dosesRequired: 2,
        scheduleIntervals: [0, 4],
        boosterIntervalMonths: 60,
        requiresBooster: true,
        storageTempMin: 2,
        storageTempMax: 8,
        shelfLifeMonths: 36,
        storageInstructions: 'Conserver entre 2-8C',
        contraindications: ['allergie_grave'],
        precautions: ['maladie_febrile'],
        sideEffects: ['douleur_locale', 'rougeur'],
        adverseReactions: ['reactions_allergiques'],
        diseasesPrevented: ['tetanos_maternel', 'tetanos_neonatal'],
        efficacyRate: '95-100%',
        immunityDurationYears: 5,
        isWhoApproved: true,
        isNationalProgram: true,
        isMandatory: true,
        priorityLevel: 1,
        status: 'active',
        syncId: uuidv4(),
        version: 1,
        isSynced: false
      }
    ])

    console.log('✅ Vaccine types seeded successfully')
  }
}